version: 0.2

env:
  variables:
    REGION: ap-southeast-2
    ACCOUNT: 291104527402
    SERVICE_NAME: spring-boot-aws-starter

phases:
  pre_build:
    commands:
    - REPOSITORY_URI=$ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$SERVICE_NAME
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
    - echo Environment
    - printenv
    - echo Logging in to Amazon ECR...
    - aws --version
    - $(aws ecr get-login --region $REGION --no-include-email)
  build:
    commands:
    - echo Build started on `date`
    - mvn clean verify -B
  post_build:
    commands:
    - |
      if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]
      then
        echo Build completed successfully on `date`
        echo Building the Docker image...
        docker build --build-args=target/$SERVICE_NAME-*.jar -t $REPOSITORY_URI:latest .
        docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
        echo Pushing the Docker images...
        docker push $REPOSITORY_URI:latest
        docker push $REPOSITORY_URI:$IMAGE_TAG
        echo Writing image definitions file...
        printf '[{"name":"%s","imageUri":"%s"}]' $SERVICE_NAME $REPOSITORY_URI:$IMAGE_TAG > image_definitions.json
      else
        echo Previous step failed, skipping Docker build/push
      fi

artifacts:
  files: image_definitions.json
